### ISSUE TITLE
Waterway detection and naming

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#11]
**Feature branch: `None`**

Waterways will likely serve an integral part in the narrative and functional aspects of the settlement, which is why they should be identified and given names.

### To do

- [x] Detect bodies of water
- [ ] Connect detected bodies and make inspecting connectivity accessible
- [ ] Name connected bodies for use in narration
- [ ] Mark points of interest (waterfalls, deltas etc.)

**Comment by avdstaaij** [comment]
Closing this for the same reason as #9.
