### ISSUE TITLE
Narrative text generation

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#12]
**Feature branch: `None`**

For criteria #3 #4 and #6 the ability to turn data into immersive, human-readable text would be useful.
This might include:
- [ ] Creating directional signage from start and end coordinates and location name
- [ ] Creating location descriptions/directions from various parameters
- [ ] Creating structure descriptions based on structure attributes

**Comment by avdstaaij** [comment]
Closing this along with #1, and for the same reason as #9.
