### ISSUE TITLE
Artificial feature generation

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#14]
**Feature branch: `None`**

For the sake of this issue, artificial features are objects that are continuous in nature and directly adapt to the surrounding topology.
For finite objects, see #9
Many of these objects may be part of an area, see #10 

## Transport
- [ ] Stepping stones: crossing shallow water
- [ ] ***(essential)*** Paths: connecting points of interest *([inspiration](https://youtu.be/eSprODXIBvM))*
- [ ] Canals: connecting bodies of water
- [ ] Bridges: crossing ravines or deep water
- [ ] Tunnels: connecting through mountains
- [ ] Railways: transport of heavy goods for short distances
- [ ] Secret tunnels between points of interest

## Food, drink and health
- [ ] Irrigation: channels connected to freshwater source (in rows spaced by 8 blocks)
- [ ] Sewage: channels connecting houses to freshwater source
- [ ] Crop field: monoculture farmland
- [ ] Pasture: grassy plains for keeping livestock on farmland
- [ ] Fencing: surrounding areas and dangers
- [ ] Hot springs: on top of lava lakes?

## Defence
- [ ] Berms: under paths along steep terrain
- [ ] Trenches/moats: surrounding fortified settlement
- [ ] Flood wall: along riverbank for settlements prone to flooding
- [ ] ***(essential)*** Palisades: surrounding settlement
- [ ] Defensive wall: surrounding settlement

## Industry
- [ ] Mineshaft: Strip-mine or cave supports
- [ ] Quarry: By exposed rock
- [ ] Scaffolding: On quarries and buildings under construction

## Culture
- [ ] Climbing site: on steep mountainsides
- [ ] Ice skating rink: on frozen water

## Decoration
- [ ] Fences / walls along paths

**Comment by avdstaaij** [comment]
Closing this for the same reason as #9.
