### ISSUE TITLE
Chronicle treasure-hunt

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#16]
**Feature branch: `None`**

For the chronicle challenge (see #6) it would be fun to turn write a story that is spread across points of interest of the map.

## Story Fragment Suggestions
1. Troglo is a villager living in a vanilla village (may be outside of build area)
2. Vanilla village is attacked and 
3. Troglo is forced to flee to a cave

## Locations with Story Fragment
- Troglo's burial mound (essential)
- Troglo's cave (essential)
- Bottom of a lake
- Illager historian's house

**Comment by avdstaaij** [comment]
Closing this along with #1.
