### ISSUE TITLE
Settlement location determination

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#17]
**Feature branch: `None`**

Determine starting location to place settlement

## To do
- [ ] (essential) Determine flat areas
- [x] Determine places near water (#11)
- [ ] Determine defensible places
- [ ] Determine places with high traffic (#8)
- [ ] Determine places rich in resources
- [ ] Determine beautiful places
- [ ] (essential) Determine starting chunk

**Comment by avdstaaij** [comment]
Closing this along with #1
