### ISSUE TITLE
Criterion: Adaption to Environment and Terrain

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#2]
**Feature branch: `None`**

One of the criteria for GDPC 2022 is 'Adaption to Environment and Terrain'
It may include:
- [ ] Sensible choice for settlement location
- [ ] Awareness of potential and hazards of natural features
- [ ] Respects pre-existing topology
- [ ] Usage of local resources
- [ ] Adaption of buildings to climate (see #5)
- [ ] Adaption of environment to overcome problems (see #3)
- [ ] Distinction of housing quality based on land value

## Ideas

- Settlement seed near water on largest region of flat terrain (for easy expansion)
- Transformation of lava lakes into hot springs (magma blocks under water)
- Marking waterfalls as points of interest (secret cave behind waterfall?)
- Marking cliff-faces for mines and quarries, forests for forestry

**Comment by avdstaaij** [comment]
Closing this along with #1
