### ISSUE TITLE
Criterion: Functionality from an Embodied Perspective

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#3]
**Feature branch: `None`**

One of the criteria for GDPC 2022 is 'Adaption to Environment and Terrain'
It may include:

- [ ] Accessibility and mobility between structures
- [ ] Accessibility and mobility between points of interest
- [ ] Protection from mob spawning
- [ ] Protection from external forces
- [ ] Implementation of traps and other defensive measures
- [ ] Access to food
- [ ] Access to water
- [ ] Access to manufactured goods
- [ ] Access to exotic goods/trade
- [ ] Access to other dimensions
- [ ] Protection against realistic, but unimplemented effects (e.g. heavy rain/snowfall, flooding)

## Ideas

- Paths of differing quality (occasional coarse dirt for wild trail, wide, paved streets for main streets)
- Signposting direction of points of interest at crossings
- Looting and pillaging of local structures
- Usage of ferries to cross rivers
- Walled settlement (wooden pikes at first, masonry when most advanced)
- Moats and embankments
- Wells where sensible, irrigation systems in arid regions
- Special nether portal location (fortified against zombie pigmen)
- Excavated and activated end portal if within build area (/locate to check)
- Avalanche protection (snowy mountains)

**Comment by avdstaaij** [comment]
Closing this along with #1
