### ISSUE TITLE
Expand biome lookups

### ISSUE THREAD

**Issue by avdstaaij** [avdstaaij/gdpc#31]
Moved from https://github.com/nilsgawlik/gdmc_http_client_python/issues/54, by @Flashing-Blinkenlights:

---

It would make sense to have certain values of biomes accessible, for example type and temperature.
A possible way to implement this might be using enums, but this requires further investigation.

**Comment by Niels-NTG** [comment]
It would be possible to further biome information in the `/biomes` endpoint in [GDMC-HTTP](https://github.com/Niels-NTG/gdmc_http_interface), even though this is not a proper lookup table in GDPC itself.

If we go this route, the API would look something like this:
`OPTIONS /biome?name=minecraft:snowy_plains`
```json
{
  grassColor: 8434839,
  waterColor: 4159204,
  temperature: 0.0
}
```
https://nekoyue.github.io/ForgeJavaDocs-NG/javadoc/1.19.2/net/minecraft/world/level/biome/Biome.html

**Comment by avdstaaij** [comment]
I think it would be better if clients (here: GDPC) contained a lookup table for this. This keeps the API more minimal and removes unnecessary HTTP requests. Do you think you could extract such a lookup table?

**Comment by Niels-NTG** [comment]
Instead of compiling the lookup table ourselves we could also rely on https://github.com/SpockBotMC/python-minecraft-data , right?

**Comment by avdstaaij** [comment]
Indeed! I'd argue we could just recommend that package for these types of lookups in the readme.

**Comment by avdstaaij** [comment]
Looking back at this, I think that recommending https://github.com/SpockBotMC/python-minecraft-data is definitely the way to go here. That repository seems well-maintained, and it provides all relevant information. I see no need to duplicate it in GDPC. Closing this as wontfix.
