### ISSUE TITLE
visualizeMap.py throwing error with unloaded chunks

### ISSUE THREAD

**Issue by avdstaaij** [avdstaaij/gdpc#34]
Moved from https://github.com/nilsgawlik/gdmc_http_client_python/issues/59, by @Flashing-Blinkenlights:
See https://github.com/nilsgawlik/gdmc_http_client_python/issues/59 for more discussion, another bug, and a fix for it.

---

When an IndexError appears due to unloaded chunks, return a more user-friendly message.

**Comment by avdstaaij** [comment]
Just like #18, I cannot reproduce this bug. Even when working with a build area 100,000 blocks away, everything seems to work just fine. I suspect that the bug has been solved somewhere along the way, either in GDPC or in GDMC-HTTP. I'm closing this issue, but feel free to open a new one if the bug still occurs.

**Comment by Niels-NTG** [comment]
The current version of GDMC-HTTP can easily deal with world positions that aren't loaded (yet). This doesn't seem to be the case with the old 1.16.5 version.
