### ISSUE TITLE
Criterion: Believable and Evocative Narrative

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#4]
**Feature branch: `None`**

One of the criteria for GDPC 2022 is 'Believable and Evocative Narrative', which should be implemented in an implicit way
It may include:

- [ ] History of the settlement (visible)
- [ ] History of the people inhabiting the settlement
- [ ] Culture and beliefs of the people inhabiting the settlement
- [ ] Distinct visual/architectural identity (see #5)

## Ideas

- Settlers are illagers that have migrated from across the ocean (Viking-inspired)
- Settlers are illagers who wish to reclaim their lands (native American-inspired)
- Ship burials under earthen mounds
- Belief in a pantheon (Mojang?)

**Comment by avdstaaij** [comment]
Closing this along with #1
