### ISSUE TITLE
Criterion: Visual Aesthetics

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#5]
**Feature branch: `None`**

One of the criteria for GDPC 2022 is 'Visual Aesthetics'
It may include:

- [ ] Variations/parametrisation of structures
- [ ] Usage of sight lines (uninterrupted view of landmarks from between buildings)
- [ ] Usage of a limited and tasteful palette
- [ ] Usage of textures and interesting geometry
- [ ] Unique decoration
- [ ] Choice of materials, architecture and decoration reflect narrative

## Ideas

- Early medieval, viking-inspired architecture (adaptation to desert?)

**Comment by avdstaaij** [comment]
Closing this along with #1
