### ISSUE TITLE
Design of interface.py

### ISSUE THREAD

**Issue by avdstaaij** [avdstaaij/gdpc#54]
# Design of interface.py

I am currently significantly refactoring GDPC (on the `refactor` branch). Since
the refactor will break compatibility all over the place anyway, I would like to
take the opportunity to make the design of GDPC as good as possible.
However, there are a few design aspects related to `interface.py` for which I
find it difficult to make a decision. I would like to hear the opinion of others
on these aspects.

First, I will give some background, and then, I will explain the design
questions.

## The current "entities"

On `master`, there are currently four "entities" that directly interact with
the HTTP interface:
- `direct_interface` (free functions)
- `interface` (free functions)
- `interface.Interface`
- `WorldSlice`

On `refactor`, `interface.Interface` is renamed to `interface.Editor`, but
otherwise the entities are the same.

The responsibilities of the "entities" are as follows:
- `direct_interface` contains only _direct_ Python bindings for the HTTP
  interface, and has minimal dependencies. It is not intended to be used
  by developers, but may be useful if they want to create their own higher-level
  classes.

- The free functions in `interface` perform stateless Minecraft operations, such
  as executing commands or getting the build area

- `Editor` contains functions to place and get blocks, contains lots of state
  to make this easier or more efficient, and contains other functions that also
  require this state. It has a lot of responsibilities, but it cannot be broken
  up any further due to the shared state (for example, both `getBlock` and
  `setBlock` need to access the block cache if caching is enabled).

- `worldSlice` contains logic to call the `GET /bytes` endpoint and parse the
  result into a world slice datastructure.

Currently, the URL of the HTTP interface is hardcoded to
`http://localhost:9000`. I would like to make this configurable, ideally in the
next update to avoid future compatibility issues. I would rather avoid requiring
developers to pass a URL parameter to every interface-related function if they
use a non-default url, so I would prefer if the URL was stored as state.

I would also like to make the interface-related error reporting of GDPC
configurable. Currently, GDPC prints errors to stderr, but users may
not want this. This setting should also be stored as state.

Note that *all* interface-related entities would depend on these two bits of
state.

My first thought is to add an `Interface` class (do not confuse with the old
`Interface` class on `master`, which is now called `Editor`), and to put this
state (url, error logging setting) into it along with the free functions from
`interface.py`. Both `Editor` and the `WorldSlice` constructor would require
`Interface` to get this url and error logging info.

So, assuming the plan described above, the entities and their state are as follows:
- `direct_interface` has no state
- `Interface` state:
  - URL
  - Error logging setting
- `Editor` state:
  - `Interface`
  - Local coordinate transform (translation, rotation, flip)
  - Block buffer
  - Block cache
  - Block placement settings
  - etc.
- `WorldSlice` constructor has no state

## Design questions

There are two related design questions for which I find it difficult to make a
decision:
1. To what degree should `Interface` and `Editor` be global?
2. Does splitting `Interface` and `Editor` make sense? Should they be merged?

I will go in more detail for both.

### Question 1 - To what degree should Interface and Editor be global?

`Interface` and `Editor` are both "entities" with state. There are (at least)
four ways to implement an entity with state, each with advantages and
disadvantages:

1. Put the state in global variables and implement the entity with free
   functions. Equivalent to a singleton class.
   
   *Advantages:*
   - Easiest to use, developers need not even know about the existence of state
     unless they want to change it.
   - No classes to pass around.
   
   *Disadvantages:*
   - It becomes *impossible* to have multiple instances of the entity. This
     is the only option that makes something impossible.
   - It is "magic"-y: it may be hard to developers to understand which function
     calls affect others, since state is hidden away.

2. Implement the entity as a class.

   *Advantages:*
   - Multiple instances are possible.
   - Simplest and cleanest design from the perspective of GDPC.
   - Good discoverability via code completion on a class instance.
   
   *Disadvantages:*
   - Developers need to instantiate the classes, making GDPC slightly more
     difficult to use.
   - Class instances need to be passed around everywhere. Developers are forced
     to add parameters for the classes in nearly all of their functions, again
     making GDPC slightly more difficult to use.

3. Combination of option 1 and 2: implement the entity as a class, but create
   a default instance of it and add free functions that work with this default
   instance. This is how `Editor` (previously called `Interface`) is implemented
   on `master`.
   
   *Advantages:*
   - Both the advantages of options 1 and 2: developers can choose.
   
   *Disadvantages:*
   - All functions of the entity need to be duplicated (methods and free
     functions). Perhaps multiple duplications are even needed, for example if
     `Interface` has a default `Editor` and there is also a default `Interface`.
     This is somewhat painful to maintain, and may even cause name collision
     issues.
   - Difficult to understand for both GDPC contributors and generator
     developers.

4. Implement the entity as free functions and require that all state is
   managed by the caller and is passed to each function as parameters.
   `direct_interface` and the `worldSlice` constructor are implemented in this
   way, but I find it unacceptable for `Interface` and `Editor`.

This is all quite abstract, so I'll give some representative syntax examples of
option 1 and option 2 (for option 3, developers can choose either syntax).

`Interface` global (option 1), `Editor` global (option 1):
```python
def buildHouse(position):
	runCommand("say 'building house!'")
	placeCuboid(position, position+10, hollow=True)
	...

setURL("http://example.com:9000")
setBuffering(True)

worldSlice = WorldSlice(Rect((0,0), (64,255,64)))
placeBlock((0,64,0), Block("stone"))
buildHouse((10,64,0))
```

`Interface` global (option 1), `Editor` as class (option 2):
```python
def buildHouse(editor, position):
	runCommand("say 'building house!'")
	placeCuboid(editor, position, position+10, hollow=True)
	...

setURL("http://example.com:9000")

editor = Editor(buffering=True)

worldSlice = WorldSlice(Rect((0,0), (64,255,64)))
editor.placeBlock((0,64,0), Block("stone"))
buildHouse(editor, (10,64,0))
```

`Interface` as class (option 2), `Editor` global (option 1) (this one makes
little sense, but also see design question 2):
```python
def buildHouse(interface, position):
	interface.runCommand("say 'building house!'")
	placeCuboid(position, position+10, hollow=True)
	...

interface = Interface(url="http://example.com:9000")

setInterface(interface)
setBuffering(True)

worldSlice = WorldSlice(interface, Rect((0,0), (64,255,64)))
placeBlock((0,64,0), Block("stone"))
buildHouse(interface, (10,64,0))
```

`Interface` as class (option 2), `Editor` as class (option 2):
```python
def buildHouse(interface, editor, position):
	interface.runCommand("say 'building house!'")
	placeCuboid(editor, position, position+10, hollow=True)
	...

interface = Interface(url="http://example.com:9000")

editor = Editor(interface)
editor.setBuffering(True)

worldSlice = WorldSlice(interface, Rect((0,0), (64,255,64)))
editor.placeBlock((0,64,0), Block("stone"))
buildHouse(interface, editor, (10,64,0))
```

### Question 2 - Should Interface and Editor be merged?

I'm also not sure if it even makes sense to split `Interface` and `Editor`.
The reasons for splitting them is that the combined entity would have a *lot* of
state and responsibilities, which is not desirable from a software design
perspective, and that there might be cases where it is useful to have multiple
Editors for a single Interface. However, having them as one class might be much
easier for developers.

`Editor` can be merged into `Interface` by simply flattening it: all state and
methods of `Editor` become state and methods of `Interface`.

If `Interface` and `Editor` are merged, two syntaxes remain for design
question 1:

`Interface` global:
```python
def buildHouse(position):
	runCommand("say 'building house!'")
	placeCuboid(position, position+10, hollow=True)
	...

setURL("http://example.com/9000")
setBuffering(True)

worldSlice = WorldSlice(Rect((0,0), (64,255,64)))
placeBlock((0,64,0), Block("stone"))
buildHouse((10,64,0))
```

`Interface` as class:
```python
def buildHouse(interface, position):
	interface.runCommand("say 'building house!'")
	placeCuboid(interface, position, position+10, hollow=True)
	...

interface = Interface(url="http://example.com/9000")
interface.setBuffering(True)

worldSlice = WorldSlice(interface, Rect((0,0), (64,255,64)))
interface.placeBlock((0,64,0), Block("stone"))
buildHouse(interface, (10,64,0))
```

## Feedback

Which options do you think are best for both questions? Do you have an entirely
different idea? I would like to hear!

I am currently slightly leaning towards merging `Interface` and `Editor` into
just `Interface`, and implementing `Interface` as option 3 (as class, but
with a default instance and free functions that work with the default instance).

**Comment by Niels-NTG** [comment]
To reduce complexity/confusion for the user, I would at consider merging `direct_interface` and `Interface` into the same file, where some or all of the methods now used for the direct interface are static.

Likewise I would also consider making `WorldSlice` a part of `Interface` and have the user interact with the data of `WorldSlice` via the `Interface`, since the chunk data is useful for caching. It allows you to quickly look up a block or biome at a given location without having to do a request.

Quick note on the URL: It's non-trivial to implement in [[GDMC-HTTP](https://github.com/Niels-NTG/gdmc_http_interface/)](https://github.com/Niels-NTG/gdmc_http_interface/) a way for the user to change the port, which is now 9000. But if there is a need for this I will look into a way for the user to change this inside of Minecraft.

Having said that, splitting `Interface` and `Editor` would make sense. `Interface` should be concerned managing the state such as the cache and if needed updating the cache and doing requests to `direct_interface`. `Editor` meanwhile does not contain state except for an instance of `Interface` which can be passed in its constructor. `Editor` is consequently quite a bare-bones class that invites users to create their own versions/extensions.

```python
import Interface
import Editor

interfaceInstance = Interface(url='http://localhost:9000')
mainEditor = Editor(interfaceInstance)
```

```python
import Interface
import Block

class Editor:
    
    def __init__ (self, interface: Interface):
        self.interface = interface
        
    def buildHouse(x, y, z, house):
        for block in house:
            if isinstance(block, Block)
            	self.interface.setBlock(block)
        self.interface.sendBlocks()
        
    def placeCubiod(x1, y1, z1, x2, y2, z2):
        interface.runCommand('fill %s %s %s %s %s %s' % (x1, y1, z1, x2, y2, z2))
    
```

**Comment by avdstaaij** [comment]
I'm not sure about merging `direct_interface` and `interface`. In my eyes, `direct_interface` contains only low-level python bindings, while `Interface` is slightly higher level. Users will never need to use `direct_interface`, so I don't expect much confusion. Static methods are also not that necessary in Python, since free functions exist.

`WorldSlice` will indeed be better integrated/become part of `Interface`. I think I'll keep it optional to cache it for block retrieval though, since such caching assumes nothing else is changing the world. GDPC and the HTTP mod are of course intended for the competition, but I would prefer if the system is usable more broadly, including contexts where the world _is_ being changed (e.g. by players).

About the url: this is just a bit of future-proofing. I'd like the GDPC to support an arbitrary host url in case that ever becomes useful.

I don't really understand your suggestion on how to split `Interface` and `Editor`. If `Editor` contains no state, why make it a class at all? Why not just provide free functions? Functions like `buildHouse` should definitely not be part of `Editor`, otherwise you end up with an enormous blob class. The only reason `Interface` and `Editor` are currently split, is that `Editor` contains some state that is not relevant for the rest of the interface (like the block cache).

**Comment by avdstaaij** [comment]
I'll go for the following design:

- `HTTPInterface` becomes a class with the URL as state, and all current `direct_interface` functions as members. There will be a default instance with the default URL.
- `Editor` becomes what is currently `interface.py` on `master`; the `Interface` and `Editor` classes of `refactor` will be merged into `Editor`. `Editor` will be constructed with a `HTTPInterface` instance, the default interface by default. There will be no default `Editor`: users have to construct one (following "There should be one-- and preferably only one --obvious way to do it.").

This design makes it possible to create a duck interface and feed that to an Editor (e.g. an interface that saves placements to a structure file instead of actually placing them).
