### ISSUE TITLE
Criterion: Chronicle

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#6]
**Feature branch: `None`**

One of the criteria for GDPC 2022 is 'Chronicle
It may include:

- [ ] Intricate books and signage
- [ ] Documentation of past events which shaped the settlements
- [ ] Documentation of additional context (beliefs, rituals etc.)
- [ ] Biographies of individual people
- [ ] High uniqueness compared to other maps (same generator)

## Ideas
- [ ] Story of girl who became victim to illager invasion
- [ ] Fragments of story dispersed throughout world to encourage exploration
- [ ] Describing points of interest using landmark positions (e.g. 'north of the mines', 'centre of the lake')

**Comment by avdstaaij** [comment]
Closing this along with #1
