### ISSUE TITLE
Placing a multi-block object (e.g. door) only partially updates caches

### ISSUE THREAD

**Issue by avdstaaij** [avdstaaij/gdpc#65]
Thanks to a change in [GDMC-HTTP](https://github.com/Niels-NTG/gdmc_http_interface), placing one part of a multi-block object such as a door or a bed results in the full object being placed. This feature is generally very convenient, but it does cause a small issue in GDPC: GDPC is not made aware of any additional block changes besides the one it explicitly sent, so any `Editor` caches (`_buffer`, `_cache`, `_worldSliceDecay`) may become invalid.

---

To reproduce:
```python
from gdpc import Editor, Block
from gdpc.vector_tools import Y, addY

editor = Editor(caching=True)

buildArea = editor.getBuildArea()
pos = addY(buildArea.toRect().center, 100)

editor.placeBlock(pos,       Block("stone_bricks"))
editor.placeBlock(pos + 2*Y, Block("red_concrete"))
editor.placeBlock(pos +   Y, Block("oak_door")) # Overwrites the red concrete.
block = editor.getBlock(pos + 2*Y)
print(block)
```

Expected result:
`minecraft:oak_door`

Observed result:
`red_concrete`

---

This bug seems quite difficult to fix. One way might be to check for each placed block whether the block is part of a multi-block object and update the caches accordingly. That would however require quite some restructuring of GDPC and might hurt performance - I would rather avoid it.

**Comment by Niels-NTG** [comment]
On the side of GDMC-HTTP I may be able to make something that makes multi-part block return the ID, block data and location of it's counterpart (eg. the other half of a bed or top of a door). Would that help?

**Comment by avdstaaij** [comment]
That would certainly help!
To be future-proof, it should perhaps support multi-block objects with more than two blocks as well.

**Comment by Niels-NTG** [comment]
After some research it turns out this isn't actually possible. Or at least not in a generic way. The only thing I could do is write custom logic for every type of multi-part block.

**Comment by avdstaaij** [comment]
I was kinda afraid of that. It would still be a nice feature to have, but it's not really essential. This custom logic could in principle also be added to GDPC (though other frontends would then of course not benefit from it).

In the end, I think this is a pretty low-priority bug. I'd be surprised if anyone even notices it. So long as no-one complains, I'm fine with leaving this as-is.

**Comment by Niels-NTG** [comment]
And besides, due to the nature of writing and reading to a live Minecraft world, cache integrity can't be guaranteed no matter what. Blocks may can be removed, placed or changed via player interaction or "natural phenomena" such as fire, water, lava, spawning and de-spawning of mobs and other entities, explosions, red stone interactions, etc.
