### ISSUE TITLE
Pathfinding and navigation

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#8]
**Feature branch: `None`**

To create sensible navigational networks pathfinding will be essential.
This might include:

- [ ] ***(essential)*** Pathfinding from point-to-point
- [ ] Identifying crossroads
- [ ] Classifying connection traffic volume
- [ ] Taking terrain steepness into account
- [ ] Determining where staircases should be built
- [ ] Determining where bridges or tunnels should be built
- [ ] Determining where piers for waterways should be built
- [ ] Determining where stables for horses should be built
- [ ] Determining where minecart railways should be built
- [ ] Determining where Nether portals should be built

**Comment by avdstaaij** [comment]
Closing this as duplicate in favor of #29.
Some of the points here are wontfixes for the same reason as #9.
