### ISSUE TITLE
"connection aborted" on trying to place blocks

### ISSUE THREAD

**Issue by tenpn** [avdstaaij/gdpc#87]
I've tried this with emerald-city and quick_example, but 1_hello_block.py current does not run for me. 

On editor.placeBlock on line 32, the connection aborts after several retries. emerald-city seems to manage to make a lot of the buildPerimeter placeCuboid calls before aborting, but when I check in-game I don't see anything. emerald-city gets through the ED.loadWorldSlice line, so at one point it's able to communicate with the game. 

It's entirely possible I've either messed up the setup, or the problem lies outside GDPC, but any help on diagnostics would be appreciated. 

I'm on minecraft 1.19.3, forge 44.1.23, GDMC HTTP 1.2.3, and GDPC 6.1.1.

**Comment by Niels-NTG** [comment]
GDMC HTTP version 1.0.0 and above are specifically make to work with Minecraft version 1.19.2 and Forge 43.2.0. Other versions such as 1.19.3 aren't supported officially, hence stuff might break.
